services:
  - type: web
    name: mercadoexpress-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api-v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLUSTER_DB_MONGO
        sync: false
      - key: USER_DB_MONGO
        sync: false
      - key: PASSWORD_DB_MONGO
        sync: false
      - key: NAME_CONTAINER_DB_MONGO
        value: ceiba-mercadoexpress
      - key: KEEPALIVE_URL
        value: https://prueba-ceiba-mercadoexpress.onrender.com/api-v1/health
      - key: KEEPALIVE_INTERVAL_MINUTES
        value: "10"
      - key: CORS_ORIGINS
        value: https://prueba-ceiba-frontend.onrender.com

  - type: web
    name: prueba-ceiba-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://prueba-ceiba-mercadoexpress.onrender.com/api-v1
